### ISSUE TITLE
[1.18.2-1.19.2] Crash on entering save 进入世界崩溃

### ISSUE THREAD

**Issue by Dr-WeiAL** [LimonBlaze/origins-accessibilities#2] opened 2022-08-27 16:23 UTC
**Description**
在安装了此mod后进入世界会崩溃
Game crashes on entering save with this mod installed

**Steps to reproduce:**
已经排查到只安装机械动力和起源，仍然会导致崩溃
Crashes still occurs when only Create and Origins: Accessibilities are installed

**Expected behavior:**
游戏正常运行
Game running normally

**Logs**
[crash-2022-08-28_00.18.30-client.txt](https://github.com/LimonBlaze/origins-accessibilities/files/9438307/crash-2022-08-28_00.18.30-client.txt)

**Screenshots**

**Mod list:**
caelus-forge-1.18.1-3.0.0.2.jar
curios-forge-1.18.2-5.0.7.1.jar
flywheel-forge-1.18.2-0.6.5.jar
Origins-1.18.2-1.4.1.4-unified.jar
create-1.18.2-0.5.0.d.jar
origins-accessbilities-1.18.2-1.0.1.jar

**Comment by RaymondBlaze** [comment] 2022-08-27 16:26
<del>已确认，应该是机械动力版本太高的缘故，目前的版本基于0.5.0.c，现在正在着手更新对应0.5.0.d的版本
Confirmed, should be caused by a higher version of Create. Origins: Accessibilities currently based on 0.5.0.c, will be working on a new release for 0.5.0.d.</del>
经测试发现其实是mixin remap问题，已于1.18.2-1.0.2和1.19.2-1.1.1修复
After test, it turned out being a mixin remap problem, fixed in 1.18.2-1.0.2 and 1.19.2-1.1.1

**Comment by Dr-WeiAL** [comment] 2022-08-27 16:26
好吧辛苦了

**Closed as completed** 2022-08-27 17:16 UTC
Labels: crash, mod interaction
